name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CD on merge to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npm run lint

  security-scanning:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit npm dependencies
        run: npm audit --audit-level=moderate || true

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/your-username/taskflow:latest

  docker-build-push:
    needs: security-scanning
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/your-username/taskflow:latest .

      - name: Push Docker image
        run: docker push ghcr.io/your-username/taskflow:latest

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          # Example: Trigger Azure CLI, Render CLI, or custom script
          ./scripts/deploy.sh
